services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: orders
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  python_app:
    image: python:3.10-slim
    container_name: python_app_container
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/orders
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python3 main.py"
    depends_on:
      - postgres

volumes:
  postgres_data:
